# Generated by Django 4.2.15 on 2024-08-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigpcol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
