# Generated by Django 4.2.15 on 2024-08-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigpcol', '0002_payment_fecha_aprobacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='banco_emisor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='numero_transaccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
