# Generated by Django 4.2.15 on 2024-08-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigpcol', '0003_payment_banco_emisor_payment_numero_transaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='documento_identidad',
            field=models.CharField(default='SIN-ID', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='banco_emisor',
            field=models.CharField(default='DESCONOCIDO', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='numero_transaccion',
            field=models.CharField(default='DESCONOCIDO', max_length=100),
            preserve_default=False,
        ),
    ]
