# Generated by Django 4.2.15 on 2024-08-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigpcol', '0004_payment_documento_identidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('NIVEL1', 'Usuarios Finales'), ('NIVEL2', 'Administradores Contables'), ('NIVEL3', 'Usuarios Administrativos'), ('NIVEL4', 'Super Administrador General')], default='NIVEL1', max_length=10),
        ),
    ]
