# Generated by Django 4.2.15 on 2024-09-04 12:55

from django.db import migrations, models
from django.utils.timezone import now


class Migration(migrations.Migration):

    dependencies = [
        ('sigpcol', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='fecha_creacion',
            field=models.DateField(default=now),  # Cambia la fecha por la actual o una predeterminada válida
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='documento_identidad',
            field=models.CharField(default='', max_length=20),
        ),
    ]
