# Generated by Django 4.2.15 on 2024-09-04 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigpcol', '0006_discount_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='fecha_creacion',
            new_name='fecha',
        ),
    ]
