# Generated by Django 4.2.15 on 2024-09-04 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigpcol', '0007_rename_fecha_creacion_discount_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='fecha',
        ),
    ]
