# Generated by Django 4.2.15 on 2024-09-04 13:00

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('sigpcol', '0008_remove_discount_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='fecha_creacion',
            field=models.DateField(default=timezone.now),
            preserve_default=False,
        ),
    ]
