# Generated by Django 4.2.15 on 2024-09-04 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sigpcol', '0011_alter_discount_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
