# Generated by Django 4.2.15 on 2024-09-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigpcol', '0012_alter_discount_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='recibo_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
